apiVersion: v1
kind: Service
metadata:
  name: mb-service-2-prod
  namespace: master-builder-prod
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mb-service-2-prod
  type: LoadBalancer
