apiVersion: v1
kind: Service
metadata:
  name: mb-service-2-pre-prod
  namespace: ns-master-builder-2
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mb-service-2-pre-prod
  type: LoadBalancer
